language: c
compiler:
  - gcc
  - clang

os:
  - linux

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - libpcap-dev
      - python3-openssl
      - python3-pip
      - python3-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunwind-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
    - TESTSUITE=1 DPDK=1
    - DPDK_SHARED=1
    - DPDK_SHARED=1 OPTS="--enable-shared"

matrix:
  include:
    - arch: ppc64le
      compiler: gcc
      env: OPTS="--disable-ssl"
    - arch: ppc64le
      compiler: gcc
      env: DPDK=1

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - wilder@us.ibm.com
